version: "3.9"

services:

  # Create service with RabbitMQ.
  message_broker:
    image: rabbitmq:3-management-alpine
    container_name: message_broker
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    command: sh -c "chown -R rabbitmq:rabbitmq /var/log/rabbitmq && rabbitmq-server"
    restart: always
    networks:
      - dev-network

#  sender:
#    container_name: sender
#    ports:
#      - 3000:3000
#    build:
#      context: .
#      dockerfile: Dockerfile-sender
#    environment:
#      AMQP_SERVER_URL: amqp://guest:guest@notifier:5672/
#    restart: always
#    networks:
#      - dev-network
#    depends_on:
#      - message_broker
#
#  notifier:
#    container_name: notifier
#    build:
#      context: .
#      dockerfile: Dockerfile-notifier
#    restart: always
#    networks:
#      - dev-network
#    depends_on:
#      - sender
#      - message_broker

networks:
  # Create a new Docker network.
  dev-network:
    driver: bridge